apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - common
  - bases/ssm.services.k8s.aws_documents.yaml
  - bases/ssm.services.k8s.aws_parameters.yaml
  - bases/ssm.services.k8s.aws_patchbaselines.yaml
  - bases/ssm.services.k8s.aws_resourcedatasyncs.yaml
